import "Services/MediaMetadata.idl";
import "Services/IPlayerService.idl";

namespace MediaPlayer
{
    [default_interface]
    runtimeclass PlaylistPage : Microsoft.UI.Xaml.Controls.Page
    {
        PlaylistPage();
        IPlayerService PlayerService { get; };
        IVector<MediaMetadata> Playlist{ get; };
    }
}
