import "ViewModels/PlaylistViewModel.idl";

namespace MediaPlayer
{
    [default_interface]
    runtimeclass PlaylistPage : Microsoft.UI.Xaml.Controls.Page
    {
        PlaylistPage();
        PlaylistViewModel ViewModel{ get; };
    }
}
