import "Framework/BindableBase.idl";
import "Framework/DelegateCommand.idl";
import "Models/MediaMetadata.idl";

namespace MediaPlayer
{
    [default_interface]
    unsealed runtimeclass InternetResourceViewModel : BindableBase
    {
        InternetResourceViewModel();

        String ErrorMessage;

        Microsoft.UI.Xaml.Input.ICommand LoadResource{ get; };
    }
}
