import "Framework/BindableBase.idl";
import "Framework/DelegateCommand.idl";
import "Models/SubtitleStream.idl";

namespace MediaPlayer
{
    [default_interface]
    unsealed runtimeclass MenuBarControlViewModel : BindableBase
    {
        MenuBarControlViewModel();
        IObservableVector<SubtitleStream> SubTracks{ get; };
        IVector<String> VideoEffects{ get; };
        Microsoft.UI.Xaml.Input.ICommand SetVideoEffect{ get; };
        Microsoft.UI.Xaml.Input.ICommand CreateSnapshotFile{ get; };
        Microsoft.UI.Xaml.Input.ICommand ChangePlaybackMode{ get; };
        Microsoft.UI.Xaml.Input.ICommand ChangePlaybackSpeed{ get; };
        Microsoft.UI.Xaml.Input.ICommand ChangeSubTrack{ get; };
        Microsoft.UI.Xaml.Input.ICommand Exit{ get; };
        Microsoft.UI.Xaml.Input.ICommand OpenFiles{ get; };
        Microsoft.UI.Xaml.Input.ICommand OpenSubtitle{ get; };
        Microsoft.UI.Xaml.Input.ICommand OpenRecorderWindow{ get; };
        Microsoft.UI.Xaml.Input.ICommand OpenInternetResourceWindow{ get; };
    }
}