import "Framework/BindableBase.idl";
import "Framework/DelegateCommand.idl";
import "Models/MediaMetadata.idl";

namespace MediaPlayer
{
    [default_interface]
    unsealed runtimeclass RecorderViewModel : BindableBase
    {
        RecorderViewModel();
        
        Double HoursStart;
        Double MinutesStart;
        Double SecondsStart;

        Double HoursEnd;
        Double MinutesEnd;
        Double SecondsEnd;

        String ErrorMessage;

        Microsoft.UI.Xaml.Input.ICommand Record{ get; };
    }
}
